### ISSUE TITLE
OSX 10.12.6+980Ti，TypeError: init_params() got an unexpected keyword argument 'allow_extra'

### ISSUE THREAD

**Issue by mawangyi** [msracver/Deformable-ConvNets#110]
Epoch[0] Batch [13900]	Speed: 3.23 samples/sec	Train-RPNAcc=0.980004,	RPNLogLoss=0.056873,	RPNL1Loss=0.037909,	RCNNAcc=0.876421,	RCNNLogLoss=0.347181,	RCNNL1Loss=0.162117,	
Traceback (most recent call last):
  File "experiments/rfcn/rfcn_end2end_train_test.py", line 19, in <module>
    train_end2end.main()
  File "experiments/rfcn/../../rfcn/train_end2end.py", line 170, in main
    ctx = [mx.gpu(int(i)) for i in config.gpus.split(',')]
  File "experiments/rfcn/../../rfcn/train_end2end.py", line 160, in train_net
    batch_end_callback=batch_end_callback, kvstore=config.default.kvstore,
  File "experiments/rfcn/../../rfcn/core/module.py", line 990, in fit
    self.set_params(arg_params, aux_params)
  File "/Library/Python/2.7/site-packages/mxnet-0.12.0-py2.7.egg/mxnet/module/base_module.py", line 652, in set_params
    allow_extra=allow_extra)
TypeError: init_params() got an unexpected keyword argument 'allow_extra'

**Comment by mawangyi** [comment]
delete “allow_extra=allow_extra”，it's work。。。
