### ISSUE TITLE
AttributeError: 'module' object has no attribute 'IMREAD_IGNORE_ORIENTATION'

### ISSUE THREAD

**Issue by imrandatascientist** [msracver/Deformable-ConvNets#122]
Hi
When I run the R-FCN demo with `python ./rfcn/demo.py` , I get the following error:

> Traceback (most recent call last):
>   File "./rfcn/demo.py", line 129, in <module>
>     main()
>   File "./rfcn/demo.py", line 69, in main
>     im = cv2.imread(cur_path + '/../demo/' + im_name, cv2.IMREAD_COLOR | cv2.IMREAD_IGNORE_ORIENTATION)
> AttributeError: 'module' object has no attribute 'IMREAD_IGNORE_ORIENTATION'

How do I get around this?

Thanks

**Comment by imrandatascientist** [comment]
Solved. You need to upgrade cv3 as only the latest version has this feature.
