### ISSUE TITLE
Got error when running demo. (Operator _zeros cannot be run)

### ISSUE THREAD

**Issue by Zehaos** [msracver/Deformable-ConvNets#14]
Thanks for the great work.

I followed the installation steps but got error when running 'python ./rfcn/demo.py'

### Environment
Ubuntu16.04, GCC 5.4
GTX1060
MXNet Installation validated successfully.

### Error:
```
[15:00:14] src/c_api/c_api_ndarray.cc:392: Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered
```

### Full:
```
(mxnet) xx@xx-xx:~/PycharmProjects/Deformable-ConvNets-master$ python ./rfcn/demo.py 
{'CLASS_AGNOSTIC': True,
 'MXNET_VERSION': 'mxnet',
 'SCALES': [(600, 1000)],
 'TEST': {'BATCH_IMAGES': 1,
          'CXX_PROPOSAL': False,
          'HAS_RPN': True,
          'NMS': 0.3,
          'PROPOSAL_MIN_SIZE': 0,
          'PROPOSAL_NMS_THRESH': 0.7,
          'PROPOSAL_POST_NMS_TOP_N': 2000,
          'PROPOSAL_PRE_NMS_TOP_N': 20000,
          'RPN_MIN_SIZE': 0,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'max_per_image': 100,
          'test_epoch': 8},
 'TRAIN': {'ALTERNATE': {'RCNN_BATCH_IMAGES': 0,
                         'RPN_BATCH_IMAGES': 0,
                         'rfcn1_epoch': 0,
                         'rfcn1_lr': 0,
                         'rfcn1_lr_step': '',
                         'rfcn2_epoch': 0,
                         'rfcn2_lr': 0,
                         'rfcn2_lr_step': '',
                         'rpn1_epoch': 0,
                         'rpn1_lr': 0,
                         'rpn1_lr_step': '',
                         'rpn2_epoch': 0,
                         'rpn2_lr': 0,
                         'rpn2_lr_step': '',
                         'rpn3_epoch': 0,
                         'rpn3_lr': 0,
                         'rpn3_lr_step': ''},
           'ASPECT_GROUPING': True,
           'BATCH_IMAGES': 1,
           'BATCH_ROIS': -1,
           'BATCH_ROIS_OHEM': 128,
           'BBOX_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZATION_PRECOMPUTED': True,
           'BBOX_REGRESSION_THRESH': 0.5,
           'BBOX_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_WEIGHTS': array([ 1.,  1.,  1.,  1.]),
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'CXX_PROPOSAL': False,
           'ENABLE_OHEM': True,
           'END2END': True,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'FLIP': True,
           'RESUME': True,
           'RPN_BATCH_SIZE': 256,
           'RPN_BBOX_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 0,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 300,
           'RPN_PRE_NMS_TOP_N': 6000,
           'SHUFFLE': True,
           'begin_epoch': 5,
           'end_epoch': 8,
           'lr': 0.0005,
           'lr_factor': 0.1,
           'lr_step': '5.333',
           'model_prefix': 'e2e',
           'momentum': 0.9,
           'warmup': False,
           'warmup_lr': 5e-05,
           'warmup_step': 1000,
           'wd': 0.0005},
 'dataset': {'NUM_CLASSES': 81,
             'dataset': 'coco',
             'dataset_path': './data/coco',
             'image_set': 'train2014+val2014',
             'proposal': 'rpn',
             'root_path': './data',
             'test_image_set': 'test-dev2015'},
 'default': {'frequent': 20, 'kvstore': 'device'},
 'gpus': '0',
 'network': {'ANCHOR_RATIOS': [0.5, 1, 2],
             'ANCHOR_SCALES': [4, 8, 16, 32],
             'FIXED_PARAMS': ['conv1',
                              'bn_conv1',
                              'res2',
                              'bn2',
                              'gamma',
                              'beta'],
             'FIXED_PARAMS_SHARED': ['conv1',
                                     'bn_conv1',
                                     'res2',
                                     'bn2',
                                     'res3',
                                     'bn3',
                                     'res4',
                                     'bn4',
                                     'gamma',
                                     'beta'],
             'IMAGE_STRIDE': 0,
             'NUM_ANCHORS': 12,
             'PIXEL_MEANS': array([ 103.06,  115.9 ,  123.15]),
             'RCNN_FEAT_STRIDE': 16,
             'RPN_FEAT_STRIDE': 16,
             'pretrained': './model/pretrained_model/resnet_v1_101',
             'pretrained_epoch': 0},
 'output_path': './output/rfcn',
 'symbol': 'resnet_v1_101_rfcn'}
[15:00:14] /home/zehao/mxnet/dmlc-core/include/dmlc/./logging.h:304: [15:00:14] src/c_api/c_api_ndarray.cc:392: Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered

Stack trace returned 10 entries:
[bt] (0) /home/zehao/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7fd8c20081bc]
[bt] (1) /home/zehao/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(MXImperativeInvoke+0x8c9) [0x7fd8c2e09c39]
[bt] (2) /home/zehao/anaconda2/envs/mxnet/lib/python2.7/lib-dynload/_ctypes.so(ffi_call_unix64+0x4c) [0x7fd8b930c57c]
[bt] (3) /home/zehao/anaconda2/envs/mxnet/lib/python2.7/lib-dynload/_ctypes.so(ffi_call+0x1f5) [0x7fd8b930bcd5]
[bt] (4) /home/zehao/anaconda2/envs/mxnet/lib/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x3e6) [0x7fd8b9303376]
[bt] (5) /home/zehao/anaconda2/envs/mxnet/lib/python2.7/lib-dynload/_ctypes.so(+0x9db3) [0x7fd8b92fadb3]
[bt] (6) /home/zehao/anaconda2/envs/mxnet/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x53) [0x7fd8ca996e93]
[bt] (7) /home/zehao/anaconda2/envs/mxnet/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x715d) [0x7fd8caa4980d]
[bt] (8) /home/zehao/anaconda2/envs/mxnet/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x89e) [0x7fd8caa4bc3e]
[bt] (9) /home/zehao/anaconda2/envs/mxnet/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8b47) [0x7fd8caa4b1f7]

Traceback (most recent call last):
  File "./rfcn/demo.py", line 129, in <module>
    main()
  File "./rfcn/demo.py", line 89, in main
    arg_params=arg_params, aux_params=aux_params)
  File "/home/zehao/PycharmProjects/Deformable-ConvNets-master/rfcn/core/tester.py", line 29, in __init__
    self._mod.bind(provide_data, provide_label, for_training=False)
  File "/home/zehao/PycharmProjects/Deformable-ConvNets-master/rfcn/core/module.py", line 839, in bind
    for_training, inputs_need_grad, force_rebind=False, shared_module=None)
  File "/home/zehao/PycharmProjects/Deformable-ConvNets-master/rfcn/core/module.py", line 396, in bind
    state_names=self._state_names)
  File "/home/zehao/PycharmProjects/Deformable-ConvNets-master/rfcn/core/DataParallelExecutorGroup.py", line 186, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/zehao/PycharmProjects/Deformable-ConvNets-master/rfcn/core/DataParallelExecutorGroup.py", line 272, in bind_exec
    shared_group))
  File "/home/zehao/PycharmProjects/Deformable-ConvNets-master/rfcn/core/DataParallelExecutorGroup.py", line 545, in _bind_ith_exec
    context, self.logger)
  File "/home/zehao/PycharmProjects/Deformable-ConvNets-master/rfcn/core/DataParallelExecutorGroup.py", line 523, in _get_or_reshape
    arg_arr = nd.zeros(arg_shape, context, dtype=arg_type)
  File "/home/zehao/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/ndarray.py", line 980, in zeros
    return _internal._zeros(shape=shape, ctx=ctx, dtype=dtype)
  File "<string>", line 36, in _zeros
  File "/home/zehao/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/base.py", line 84, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [15:00:14] src/c_api/c_api_ndarray.cc:392: Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered

Stack trace returned 10 entries:
[bt] (0) /home/zehao/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7fd8c20081bc]
[bt] (1) /home/zehao/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(MXImperativeInvoke+0x8c9) [0x7fd8c2e09c39]
[bt] (2) /home/zehao/anaconda2/envs/mxnet/lib/python2.7/lib-dynload/_ctypes.so(ffi_call_unix64+0x4c) [0x7fd8b930c57c]
[bt] (3) /home/zehao/anaconda2/envs/mxnet/lib/python2.7/lib-dynload/_ctypes.so(ffi_call+0x1f5) [0x7fd8b930bcd5]
[bt] (4) /home/zehao/anaconda2/envs/mxnet/lib/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x3e6) [0x7fd8b9303376]
[bt] (5) /home/zehao/anaconda2/envs/mxnet/lib/python2.7/lib-dynload/_ctypes.so(+0x9db3) [0x7fd8b92fadb3]
[bt] (6) /home/zehao/anaconda2/envs/mxnet/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x53) [0x7fd8ca996e93]
[bt] (7) /home/zehao/anaconda2/envs/mxnet/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x715d) [0x7fd8caa4980d]
[bt] (8) /home/zehao/anaconda2/envs/mxnet/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x89e) [0x7fd8caa4bc3e]
[bt] (9) /home/zehao/anaconda2/envs/mxnet/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8b47) [0x7fd8caa4b1f7]
```

**Comment by Oh233** [comment]
Please install MxNet with USE_CUDA enabled.

**Comment by Zehaos** [comment]
Thanks. It works now.

**Comment by tqx0808** [comment]
@Zehaos the same error with you,can you show me how to solve it, thanks.

**Comment by Zehaos** [comment]
@tqx0808 I sloved it by installing MxNet with USE_CUDA enabled. Please refer to the tutorial.

**Comment by DeanChan** [comment]
Same problem happened in [msracver/FCIS](https://github.com/msracver/FCIS). Solution is the same. 

Maybe it's better to point this trick out in README.md. @Oh233 

Many thanks for the great job!
