### ISSUE TITLE
FPN test code error

### ISSUE THREAD

**Issue by HoracceFeng** [msracver/Deformable-ConvNets#164]
Hi @Oh233 @msracver , here is an error I met when running the FPN test error. I am sure that the training session doesn't get any error, the logs show that at the end the FG Accuracy > 0.7, RCNN Accuracy > 0.9. 

Traceback (most recent call last):
  File "experiments/fpn/fpn_test.py", line 20, in <module>
    test.main()
  File "experiments/fpn/../../fpn/test.py", line 51, in main
    args.vis, args.ignore_cache, args.shuffle, config.TEST.HAS_RPN, config.dataset.proposal, args.thresh, logger=logger, output_path=final_output_path)
  File "experiments/fpn/../../fpn/function/test_rcnn.py", line 72, in test_rcnn
    pred_eval(predictor, test_data, imdb, cfg, vis=vis, ignore_cache=ignore_cache, thresh=thresh, logger=logger)
  File "experiments/fpn/../../fpn/core/tester.py", line 193, in pred_eval
    all_boxes[idx_class][idx_im] = soft_nms(all_boxes[idx_class][idx_im])
  File "experiments/fpn/../../fpn/../lib/nms/nms.py", line 15, in _nms
    return soft_nms(dets, thresh, max_dets)
  File "experiments/fpn/../../fpn/../lib/nms/nms.py", line 94, in soft_nms
    if dets.shape[0] == 0:
AttributeError: 'list' object has no attribute 'shape'

I have checked the list object "dets", it is a null list. Actually, even if it is null, the variable "dets" should not be a list. Anyone can help me with this?

Thx.

**Comment by HoracceFeng** [comment]
Problem solved. 
A suggestion of this code: for path-related code line, add strip('/') will be better.

THX
