### ISSUE TITLE
Error while training 

### ISSUE THREAD

**Issue by akumar14** [msracver/Deformable-ConvNets#169]
I am getting the following error while training on PascalVoC ? Any suggestion , how to tackle or why is this happening. 
I run the following command and followed the training preparation process according to the given instructions.  

Traceback (most recent call last):
  File "experiments/rfcn/rfcn_end2end_train_test.py", line 19, in <module>
    train_end2end.main()
  File "experiments/rfcn/../../rfcn/train_end2end.py", line 165, in main
    config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
  File "experiments/rfcn/../../rfcn/train_end2end.py", line 92, in train_net
    sym_instance.infer_shape(data_shape_dict)
  File "experiments/rfcn/../../rfcn/../lib/utils/symbol.py", line 41, in infer_shape
    arg_shape, out_shape, aux_shape = self.sym.infer_shape(**data_shape_dict)
TypeError: zip argument #2 must support iteration

**Comment by ddlee96** [comment]
The `data_shape_dict` is provided by `provide_data()` and `provide_label()` method in `DataLoader`, you may check that out.
