### ISSUE TITLE
Trainng Error

### ISSUE THREAD

**Issue by yexiguafuqihao** [msracver/Deformable-ConvNets#21]
When I train DCN model  on the pascalvoc2012 dataset,I encountered such problems.can anyone please give me a help?
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "experiments/deeplab/../../deeplab/../lib/utils/PrefetchingIter.py", line 60, in prefetch_func
    self.next_batch[i] = self.iters[i].next()
  File "experiments/deeplab/../../deeplab/core/loader.py", line 185, in next
    self.get_batch_parallel()
  File "experiments/deeplab/../../deeplab/core/loader.py", line 234, in get_batch_parallel
    rst = [multiprocess_result.get() for multiprocess_result in multiprocess_results]
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by Orpine** [comment]
it said `libpng error: Read Error`, please check your python environment to make sure your png image reading function works properly.

**Comment by yexiguafuqihao** [comment]
When I train DCN model with flip turning off (flip:False) in the *.yaml file,The error wouldn't happened,But the error would come out with flip turning on (flip:True).But I have trained my model with some extra work.

**Comment by mursalal** [comment]
@Orpine i have an error:

`num_images 2650
wrote gt roidb to ./data/cache/voc_2007_trainval_gt_roidb.pkl
append flipped images to roidb
Traceback (most recent call last):
  File "experiments/rfcn/rfcn_end2end_train_test.py", line 19, in <module>
    train_end2end.main()
  File "experiments/rfcn/../../rfcn/train_end2end.py", line 167, in main
    config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
  File "experiments/rfcn/../../rfcn/train_end2end.py", line 75, in train_net
    for image_set in image_sets]
  File "experiments/rfcn/../../rfcn/../lib/utils/load_data.py", line 11, in load_gt_roidb
    roidb = imdb.append_flipped_images(roidb)
  File "experiments/rfcn/../../rfcn/../lib/dataset/imdb.py", line 211, in append_flipped_images
    assert (boxes[:, 2] >= boxes[:, 0]).all()
AssertionError`

Can you explain me this error?

**Comment by Oh233** [comment]
Apparently, there exist some bugs in your data format.

**Comment by mursalal** [comment]
@Orpine by this error can you say approximately what's wrong with my dataset?

**Comment by mursalal** [comment]
Apparently this is because of the size of the images of my dataset. All images in PASCAL VOC have size less than 500 pixels per side. While in my dataset have different sizes (800x533, 800x1200, 800x971 etc.). Is it possible to config net for such sizes?

**Comment by Oh233** [comment]
First, the coordinates should be arranged as [x1, y1, x2, y2], which is [left, upper, right, lower]. 
You may check which specific box cause this assertion failed to get more information.

**Comment by mursalal** [comment]
I solved this problem. You was right. Part of my dataset was wrong: xmin > xmax.

**Comment by zhuangyqin** [comment]
Hello， I have also met the problem， Could you tell me how so solve it，something like the flip picture have the error!!!

**Comment by zhuangyqin** [comment]
@yexiguafuqihao

**Comment by StOnEGiggity** [comment]
Actually, there may exists one problem in https://github.com/msracver/Deformable-ConvNets/blob/master/lib/dataset/imdb.py#L246 when VOC12 input type is "JPEG". And the code is training perfectly before I update the environment where the flip image is still png.My suggestion is to stop flip augmentation before checking the real bug.

**Comment by StOnEGiggity** [comment]
@YuwenXiong @Oh233  , a easy code may could be done like what I said above and I am testing it.Another reason may be the multi-processing.The bug occurs when I try to run several models parallelly
