### ISSUE TITLE
when i training cicyscades dataset, the error like this

### ISSUE THREAD

**Issue by bitwangdan** [msracver/Deformable-ConvNets#220]
num_images 2975
cityscape_leftImg8bit_train gt segdb loaded from ./data/cache/cityscape_leftImg8bit_train_gt_segdb.pkl
append flipped images to segdb
[('label', (1, 1, 768, 1024))]
providing maximum shape [('data', (1, 3, 768, 1024))] [('label', (1, 1, 768, 1024))]
{'data': (1L, 3L, 768L, 1024L), 'label': (1L, 1L, 768L, 1024L)}
./model/pretrained_model/resnet_v1_101
lr 0.0005 lr_epoch_diff [40.336] lr_iters [239999]
Traceback (most recent call last):
  File "experiments/deeplab/deeplab_train_test.py", line 20, in <module>
    train.main()
  File "experiments/deeplab/../../deeplab/train.py", line 166, in main
    config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
  File "experiments/deeplab/../../deeplab/train.py", line 160, in train_net
    arg_params=arg_params, aux_params=aux_params, begin_epoch=begin_epoch, num_epoch=end_epoch)
  File "experiments/deeplab/../../deeplab/core/module.py", line 984, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "experiments/deeplab/../../deeplab/core/module.py", line 1076, in update_metric
    self._curr_module.update_metric(eval_metric, labels)
  File "experiments/deeplab/../../deeplab/core/module.py", line 673, in update_metric
    self._exec_group.update_metric(eval_metric, labels)
  File "experiments/deeplab/../../deeplab/core/DataParallelExecutorGroup.py", line 492, in update_metric
    eval_metric.update(labels, texec.outputs)
  File "/home/danny.wd/gitlab/mxnet-ssd/mxnet/python/mxnet/metric.py", line 294, in update
    metric.update(labels, preds)
  File "experiments/deeplab/../../deeplab/core/metric.py", line 37, in update
    cls = pred[keep_inds, label]
IndexError: index 23 is out of bounds for axis 1 with size 19

in the .yaml files, the num_class is 19, can someone help me?

**Comment by distillation-dcf** [comment]
I met the same problem, how do you solve it? @bitwangdan
