### ISSUE TITLE
Exception: unknown storage type: -1 when no OHEM

### ISSUE THREAD

**Issue by HaydenFaulkner** [msracver/Deformable-ConvNets#228]
When running (training with) `resnet_v1_101_coco_trainval_fpn_dcn_end2end_ohem.yaml` with ohem set to false I get the following error to do with storage types in the backward pass of the custom functions:
```
Error in CustomOp.backward: Traceback (most recent call last):
      File "python2.7-mxnet/lib/python2.7/site-packages/mxnet/operator.py", line 1029, in backward_entry stype=stype))
      File "python2.7-mxnet/lib/python2.7/site-packages/mxnet/ndarray/sparse.py", line 1188, in _ndarray_cls
      raise Exception("unknown storage type: %s"%stype)
Exception: unknown storage type: -1
```

Any ideas on what might cause this error and how to resolve, thanks :)

**Comment by luliyucoordinate** [comment]
l

> When running (training with) `resnet_v1_101_coco_trainval_fpn_dcn_end2end_ohem.yaml` with ohem set to false I get the following error to do with storage types in the backward pass of the custom functions:
> 
> ```
> Error in CustomOp.backward: Traceback (most recent call last):
>       File "python2.7-mxnet/lib/python2.7/site-packages/mxnet/operator.py", line 1029, in backward_entry stype=stype))
>       File "python2.7-mxnet/lib/python2.7/site-packages/mxnet/ndarray/sparse.py", line 1188, in _ndarray_cls
>       raise Exception("unknown storage type: %s"%stype)
> Exception: unknown storage type: -1
> ```
> Any ideas on what might cause this error and how to resolve, thanks :)

I have the same problem. Have you solved it?

**Comment by chituma110** [comment]
I have the same problem. Have you solved it?

**Comment by HaydenFaulkner** [comment]
Sorry guys, I never found the cause of this issue and am now working on other projects 😓
