### ISSUE TITLE
No module named skimage.draw

### ISSUE THREAD

**Issue by yfnn** [msracver/Deformable-ConvNets#239]
I have installed scikit-image using command 'pip install scikit-image'. But I still get this error? What happened?

**Comment by yfnn** [comment]
When I run 'python experiments/faster_rcnn/rcnn_end2end_train_test.py --cfg experiments/faster_rcnn/cfgs/resnet_v1_101_voc0712_rcnn_dcn_end2end.yaml'.
Errors are as follows,
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "experiments/faster_rcnn/rcnn_end2end_train_test.py", line 17, in <module>
    import train_end2end
  File "experiments/faster_rcnn/../../faster_rcnn/train_end2end.py", line 51, in <module>
    from utils.load_data import load_gt_roidb, merge_roidb, filter_roidb
  File "experiments/faster_rcnn/../../faster_rcnn/../lib/utils/load_data.py", line 9, in <module>
    from dataset import *
  File "experiments/faster_rcnn/../../faster_rcnn/../lib/dataset/__init__.py", line 4, in <module>
    from coco import coco
  File "experiments/faster_rcnn/../../faster_rcnn/../lib/dataset/coco.py", line 23, in <module>
    from .pycocotools.coco import COCO
  File "experiments/faster_rcnn/../../faster_rcnn/../lib/dataset/pycocotools/coco.py", line 54, in <module>
    from skimage.draw import polygon
ImportError: No module named skimage.draw
