### ISSUE TITLE
undefined symbol: _ZN2at7getTypeERKNS_6TensorE

### ISSUE THREAD

**Issue by xiaoliqiangxxqzz** [msracver/Deformable-ConvNets#264]
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    from dcn_v2 import dcn_v2_conv, DCNv2, DCN
  File "/home/xlq/Downloads/DCNv2-master/dcn_v2.py", line 13, in <module>
    import _ext as _backend
ImportError: /home/xlq/Downloads/DCNv2-master/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at7getTypeERKNS_6TensorE

who can tell me what is wrong with this?

**Comment by huangteng1220** [comment]
I have the same problem. Some one has solved in this: https://docker.pkg.github.com/facebookresearch/maskrcnn-benchmark/issues/985.
But this problem still happen.

**Comment by xiaoliqiangxxqzz** [comment]
I have solved it by build it again
