### ISSUE TITLE
Trainning Error

### ISSUE THREAD

**Issue by poirotZhu** [msracver/Deformable-ConvNets#32]
I got the following error when i tried to train voc data.

Error in proposal_target.infer_shape: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mxnet-0.10.0-py3.6.egg/mxnet/operator.py", line 621, in infer_shape_entry
    ret = op_prop.infer_shape(shapes)
  File "/media/dji/0871710D255E036A/Deformable-ConvNets/rfcn/operator_py/proposal_target.py", line 102, in infer_shape
    rois = rpn_rois_shape[0] + gt_boxes_shape[0] if self._batch_rois == -1 else self._batch_rois
IndexError: list index out of range

And I found that in_shape[1] is NONE in the infer_shape function (line 100) of rfcn/operator_py/proposal_target.py  and in_shape[0] is [300 5]

**Comment by moyans** [comment]
did you solve it? i also met this problem.
