### ISSUE TITLE
The training was suspended in the middle but did not end, the GPU-Util become 0%.

### ISSUE THREAD

**Issue by realwill** [msracver/Deformable-ConvNets#7]
Thank you for sharing the wonderful work, it is really help.
I encounter problems when training.
The training suspend in epoch 0 batch 3300 (or others) and gpu-util become 0%, why?

**Comment by baiyancheng20** [comment]
How did you install mxnet? I installed it according to http://mxnet.io/, but the code didn't work.

**Comment by realwill** [comment]
@baiyancheng20 yes, I installed the mxnet as http://mxnet.io

**Comment by realwill** [comment]
I  debug the training, and locate the error as https://github.com/dmlc/mxnet/issues/3724

**Comment by Oh233** [comment]
@realwill So did you fix the bug following that?

**Comment by realwill** [comment]
@Oh233 no.....

**Comment by realwill** [comment]
@Oh233 the same problem with training fcis

**Comment by realwill** [comment]
@Oh233 and the same after I use another mxnet: https://github.com/dmlc/mxnet/tree/62ecb60

**Comment by mursalal** [comment]
Hello, I have same error after Epoch[0] Batch [800] (for the second try: Batch [700]):

`Error in CustomOp.forward: Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/operator.py", line 758, in forward_entry
aux=tensors[4])
File "experiments/rfcn/../../rfcn/operator_py/proposal.py", line 137, in forward
keep = nms(det)
File "experiments/rfcn/../../rfcn/../lib/nms/nms.py", line 20, in _nms
return gpu_nms(dets, thresh, device_id)
File "gpu_nms.pyx", line 29, in gpu_nms.gpu_nms (gpu_nms.cpp:1914)
IndexError: Out of bounds on buffer access (axis 0)`

**Comment by chengshuai** [comment]
hi
@realwill @baiyancheng20 

I have compile the mxnet and copy the folder mxnet/pyhton to external/mxnet,,then run the command python ./rfcn/demo.py ,the error is 
File "./rfcn/demo.py", line 28, in <module>
    from core.tester import im_detect, Predictor
  File "/home/chengshuai/test_sample/Deformable-ConvNets-master/rfcn/core/tester.py", line 15, in <module>
    from module import MutableModule
  File "/home/chengshuai/test_sample/Deformable-ConvNets-master/rfcn/core/module.py", line 19, in <module>
    from mxnet.initializer import Uniform, InitDesc
ImportError: cannot import name InitDesc
I do not know the why the error hanppen and could you tell me the deformal convoluthon network process.  

Thank you!

**Comment by knwng** [comment]
@chengshuai you should copy mxnet/python/mxnet to external/mxnet/ and copy mxnet/lib/libmxnet.so to external/mxnet/mxnet/. Then you should modify MXNET_VERSION  in experiments/fgfa_rfcn/cfgs/fgfa_rfcn_vid_demo.yaml according to your mxnet package name.

**Comment by maozezhong** [comment]
@mursalal，hello, Have you solved the problem?

**Comment by lclalalalala** [comment]
same problem
File "gpu_nms.pyx", line 29, in gpu_nms.gpu_nms
IndexError: Out of bounds on buffer access (axis 0)

**Comment by jjprincess** [comment]
Does anybody solve this problem?
