### ISSUE TITLE
Deeplab training framework crashes on mxnet 0.11.1 version

### ISSUE THREAD

**Issue by chowkamlee81** [msracver/Deformable-ConvNets#86]
Training framework for DeepLab using Deformable convolutions crashes on mxnet 0.11.1. 
In Deformable-ConvNets-master/deeplab/train.py line no 158.
train_net(args, ctx, config.network.pretrained, config.network.pretrained_epoch, config.TRAIN.model_prefix,
              config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
**Kindly help me since my job is under trouble**
Below is the error
Traceback (most recent call last):
  File "/usr/share/pycharm/helpers/pydev/pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/usr/share/pycharm/helpers/pydev/pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/Softwares/Testing_DC/experiments/deeplab/deeplab_train_test_DC.py", line 21, in <module>
    train.main()
  File "/home/Softwares/Testing_DC/experiments/deeplab/../../deeplab/train.py", line 159, in main
    config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
  File "/home/Softwares/Testing_DC/experiments/deeplab/../../deeplab/train.py", line 153, in train_net
    arg_params=arg_params, aux_params=aux_params, begin_epoch=begin_epoch, num_epoch=end_epoch)
  File "/home/Softwares/Testing_DC/experiments/deeplab/../../deeplab/core/module.py", line 948, in fit
    for_training=True, force_rebind=force_rebind)
  File "/home/Softwares/Testing_DC/experiments/deeplab/../../deeplab/core/module.py", line 841, in bind
    for_training, inputs_need_grad, force_rebind=False, shared_module=None)
  File "/home/Softwares/Testing_DC/experiments/deeplab/../../deeplab/core/module.py", line 396, in bind
    state_names=self._state_names)
  File "/home/Softwares/Testing_DC/experiments/deeplab/../../deeplab/core/DataParallelExecutorGroup.py", line 183, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/Softwares/Testing_DC/experiments/deeplab/../../deeplab/core/DataParallelExecutorGroup.py", line 283, in bind_exec
    shared_group))
  File "/home/Softwares/Testing_DC/experiments/deeplab/../../deeplab/core/DataParallelExecutorGroup.py", line 500, in _bind_ith_exec
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.11.1-py2.7.egg/mxnet/symbol/symbol.py", line 962, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.11.1-py2.7.egg/mxnet/symbol/symbol.py", line 1058, in _infer_shape_impl
    "but '%s' is %s." % (k, type(v)))
TypeError: Arguments need to be shapes (tuple), but 'label' is <type 'list'>.

**Comment by Oh233** [comment]
MXNet changed the interface. Please use MXNet's commit version 62ecb60

**Comment by chowkamlee81** [comment]
thanks.....
